apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tc-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tc_svc
            port: 
              number: {{ .Values.service.clusterIPPort }}
          namespace: {{ .Values.deployment.namespace }}