deployment:
  name: APP_roles
  namespace: tc
  replicaCount: 2

image:
  repository: devopsmay1117/APP:v1
  pullPolicy: Always
  containerName: webapp_role
  imagePullSecrets: dockerhub
  containerPort: 3080
  
service:
  type: NodePort
  clusterIPPort: 80
  targetPort: 8080
  nodePort: 32000
